/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BuildRouteImport } from './routes/build'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiThinkRouteImport } from './routes/api/think'
import { Route as ApiSectionRouteImport } from './routes/api/section'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiFixRouteImport } from './routes/api/fix'
import { Route as ApiAssetRouteImport } from './routes/api/asset'

const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThinkRoute = ApiThinkRouteImport.update({
  id: '/api/think',
  path: '/api/think',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSectionRoute = ApiSectionRouteImport.update({
  id: '/api/section',
  path: '/api/section',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFixRoute = ApiFixRouteImport.update({
  id: '/api/fix',
  path: '/api/fix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetRoute = ApiAssetRouteImport.update({
  id: '/api/asset',
  path: '/api/asset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/api/asset': typeof ApiAssetRoute
  '/api/fix': typeof ApiFixRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/section': typeof ApiSectionRoute
  '/api/think': typeof ApiThinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/api/asset': typeof ApiAssetRoute
  '/api/fix': typeof ApiFixRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/section': typeof ApiSectionRoute
  '/api/think': typeof ApiThinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/build': typeof BuildRoute
  '/api/asset': typeof ApiAssetRoute
  '/api/fix': typeof ApiFixRoute
  '/api/plan': typeof ApiPlanRoute
  '/api/section': typeof ApiSectionRoute
  '/api/think': typeof ApiThinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/build'
    | '/api/asset'
    | '/api/fix'
    | '/api/plan'
    | '/api/section'
    | '/api/think'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/build'
    | '/api/asset'
    | '/api/fix'
    | '/api/plan'
    | '/api/section'
    | '/api/think'
  id:
    | '__root__'
    | '/'
    | '/build'
    | '/api/asset'
    | '/api/fix'
    | '/api/plan'
    | '/api/section'
    | '/api/think'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildRoute: typeof BuildRoute
  ApiAssetRoute: typeof ApiAssetRoute
  ApiFixRoute: typeof ApiFixRoute
  ApiPlanRoute: typeof ApiPlanRoute
  ApiSectionRoute: typeof ApiSectionRoute
  ApiThinkRoute: typeof ApiThinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/think': {
      id: '/api/think'
      path: '/api/think'
      fullPath: '/api/think'
      preLoaderRoute: typeof ApiThinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/section': {
      id: '/api/section'
      path: '/api/section'
      fullPath: '/api/section'
      preLoaderRoute: typeof ApiSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fix': {
      id: '/api/fix'
      path: '/api/fix'
      fullPath: '/api/fix'
      preLoaderRoute: typeof ApiFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset': {
      id: '/api/asset'
      path: '/api/asset'
      fullPath: '/api/asset'
      preLoaderRoute: typeof ApiAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildRoute: BuildRoute,
  ApiAssetRoute: ApiAssetRoute,
  ApiFixRoute: ApiFixRoute,
  ApiPlanRoute: ApiPlanRoute,
  ApiSectionRoute: ApiSectionRoute,
  ApiThinkRoute: ApiThinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
